TD_MODEL = "../model/td/td_model.pth"
TD_MODEL_CONFIG = "../model/td/detection_config.json"
TSR_MODEL = "../model/tsr/tsr_model.pth"
TSR_MODEL_CONFIG = "../model/tsr/structure_config.json"
VIETOCR_MODEL = "model/vietocr/transformerocr.pth"
CORNER_DETECTION_MODEL = "model/weights/detect_4_points.pt"
TEXT_DETECTION_MODEL = "model/weights/last.pt"
